# Generated by Django 5.2.6 on 2025-09-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasha', '0002_user_balance_topuprequest_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
