# Generated by Django 5.2.6 on 2025-09-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasha', '0003_shipment_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cargos/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
