# Generated by Django 5.2.6 on 2025-09-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasha', '0004_cargo_photo_vehicle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
