# Generated by Django 5.2.6 on 2025-10-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasha', '0005_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='shipment',
            name='cash_received_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Şu sargyt üçin komissiýa', max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Garaşylýar'), ('paid', 'Tölenildi'), ('failed', 'Şowsuz boldy')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_type',
            field=models.CharField(choices=[('stripe', 'Stripe onlaýn'), ('cash', 'Nagt / offline'), ('bank', 'Bank geçirim')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deposit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Carrier tarapyndan goýlan öňki depozit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='tx_type',
            field=models.CharField(choices=[('top_up', 'Balans doldurmak'), ('commission', 'Komissiýa tutuldy'), ('refund', 'Pul yzyna gaýtaryldy'), ('deposit_top_up', 'Depozit goýmak'), ('deposit_commission', 'Depozitden tutuldy')], max_length=30),
        ),
    ]
