# Generated by Django 5.2.6 on 2025-10-10 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasha', '0006_remove_shipment_is_paid_shipment_cash_received_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Ulag', 'verbose_name_plural': 'Ulaglar'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='gps_enabled',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='truck_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='available_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nähili gün töweregi boş'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='available_from',
            field=models.DateField(blank=True, null=True, verbose_name='Ýüklenmäge taýýar sene'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('tent', 'Tent (çadyrly)'), ('refrigerator', 'Sowadyjy'), ('open', 'Açyk platforma'), ('isotherm', 'Izotermik'), ('tank', 'Sýisternaly'), ('container', 'Konteýner daşaýjy'), ('car_transporter', 'Awtodaşaýjy'), ('other', 'Beýleki görnüş')], max_length=50, null=True, verbose_name='Kuzow görnüşi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Şäher'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kompaniýanyň ady'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontakt ady (FIO)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon belgisi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_adr',
            field=models.BooleanField(default=False, verbose_name='ADR belgisi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_ekmt',
            field=models.BooleanField(default=False, verbose_name='EKMT rugsady'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_gps',
            field=models.BooleanField(default=False, verbose_name='GPS monitor bar'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_horses',
            field=models.BooleanField(default=False, verbose_name='Konik bar'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_lift',
            field=models.BooleanField(default=False, verbose_name='Gidrolift bar'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_tir',
            field=models.BooleanField(default=False, verbose_name='TIR belgisi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Beýikligi (m)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Şahsy adam'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Uzynlygy (m)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='load_type',
            field=models.CharField(blank=True, choices=[('top', 'Üstden'), ('side', 'Gapdal tarapyndan'), ('rear', 'Yzdan'), ('full_open', 'Doly açylýan tent'), ('crossbar_remove', 'Ştangasy aýrylýan'), ('stand_remove', 'Stoýkasy aýrylýan')], max_length=50, null=True, verbose_name='Ýükleme görnüşi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ugradyş ýeri'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location_from_radius_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ugradyş radiusy (km)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='note',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Bellik'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='partial_load',
            field=models.BooleanField(default=False, verbose_name='Dogruz kabul edýär'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pay_to_card',
            field=models.BooleanField(default=False, verbose_name='Karta geçip bolar'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='possible_unload',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mümkin düşürme ýerleri'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='promote_top',
            field=models.BooleanField(default=False, verbose_name='TOP gözlegde görkez'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rate_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nagt töleg'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rate_currency',
            field=models.CharField(choices=[('tmt', 'TMT'), ('rub', 'RUB'), ('usd', 'USD'), ('eur', 'EUR')], default='tmt', max_length=5, verbose_name='Walýuta'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rate_mode',
            field=models.CharField(choices=[('has_rate', 'Bar stawka'), ('request_rate', 'Stawka soralýar')], default='has_rate', max_length=20, verbose_name='Stawka görnüşi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rate_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stawka (NDŞ bilen)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rate_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stawka (NDŞ-siz)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='stealth_mode',
            field=models.BooleanField(default=False, verbose_name='Steýls — belli firmalardan gizle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='truck_category',
            field=models.CharField(choices=[('semi_trailer', 'Polupriýep'), ('truck', 'Ýük maşyny'), ('coupling', 'Skeçka')], default='truck', max_length=20, verbose_name='Transport görnüşi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='unload_radius_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Düşürme radiusy (km)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ini (m)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='without_bargain',
            field=models.BooleanField(default=False, verbose_name='Torgsyz (söwda ýok)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Markasy'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_kg',
            field=models.PositiveIntegerField(verbose_name='Göterim kuwwaty (kg)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modeli'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Ulag suraty'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nomeri'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Kuzowyň göwrümi (m³)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ýyly'),
        ),
    ]
