# Generated by Django 5.2.6 on 2025-10-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasha', '0007_alter_vehicle_options_remove_vehicle_gps_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'Ýük', 'verbose_name_plural': 'Ýükler'},
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='price_offer',
        ),
        migrations.AddField(
            model_name='cargo',
            name='body_type',
            field=models.CharField(blank=True, choices=[('tent', 'Tent (çadyrly)'), ('refrigerator', 'Sowadyjy'), ('open', 'Açyk platforma'), ('isotherm', 'Izotermik'), ('tank', 'Sýisternaly'), ('container', 'Konteýner daşaýjy'), ('car_transporter', 'Awtodaşaýjy'), ('other', 'Beýleki görnüş')], max_length=50, null=True, verbose_name='Kuzow görnüşi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Şäher'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kompaniýanyň ady'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='company_type',
            field=models.CharField(choices=[('ooo', 'ООО'), ('ip', 'IP'), ('fl', 'Fiziki şahs'), ('self', 'Özbaşdak')], default='ooo', max_length=20, verbose_name='Firma görnüşi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontakt ady'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon belgisi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='customs_required',
            field=models.BooleanField(default=False, verbose_name='Gümrük arkaly geçýärmi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivery_time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Düşürme başlangyç wagty'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivery_time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Düşürme tamamlanýan wagty'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='direct_contract',
            field=models.BooleanField(default=False, verbose_name='Göni şertnama boýunça'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='full_truck',
            field=models.BooleanField(default=True, verbose_name='Aýry maşyn bilen daşalýar (FTL)'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='gps_required',
            field=models.BooleanField(default=False, verbose_name='GPS monitor talap edilýär'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='has_adr',
            field=models.BooleanField(default=False, verbose_name='ADR gerek'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='has_lift',
            field=models.BooleanField(default=False, verbose_name='Gidrolift gerek'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='has_pneumatic',
            field=models.BooleanField(default=False, verbose_name='Pnewmohod gerek'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='has_straps',
            field=models.BooleanField(default=False, verbose_name='Remen gerek'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='has_tir',
            field=models.BooleanField(default=False, verbose_name='TIR dokument gerek'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='load_type',
            field=models.CharField(blank=True, choices=[('top', 'Üstden'), ('side', 'Gapdal tarapyndan'), ('rear', 'Yzdan'), ('full_open', 'Doly açylýan tent'), ('crossbar_remove', 'Ştangasy aýrylýan'), ('stand_remove', 'Stoýkasy aýrylýan')], max_length=50, null=True, verbose_name='Ýükleme görnüşi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='mutual_offers_only',
            field=models.BooleanField(default=False, verbose_name='Diňe garşy teklipler'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Bellik'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='packing_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gaplaýyş görnüşi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='partial_load',
            field=models.BooleanField(default=False, verbose_name='Dogruz kabul edýär (LTL)'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='payment_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Töleg gijikmesi (b.gün)'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Nagt'), ('bank', 'Bank geçirim'), ('stripe', 'Onlaýn töleg')], default='cash', max_length=20, verbose_name='Töleg usuly'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='payment_on_unload',
            field=models.BooleanField(default=False, verbose_name='Düşürilenden soň tölenýärmi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pickup_time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Ýüklenme başlangyç wagty'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pickup_time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Ýüklenme tamamlanýan wagty'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='prepayment_percent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Öňünden töleg (%)'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='promote_top',
            field=models.BooleanField(default=False, verbose_name='TOP gözlegde görkez'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ýük sany'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='rate_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nagt stawka'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='rate_currency',
            field=models.CharField(choices=[('tmt', 'TMT'), ('rub', 'RUB'), ('usd', 'USD'), ('eur', 'EUR')], default='tmt', max_length=5, verbose_name='Walýuta'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='rate_mode',
            field=models.CharField(choices=[('has_rate', 'Bar stawka'), ('request_rate', 'Stawka soralýar')], default='has_rate', max_length=20, verbose_name='Stawka görnüşi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='rate_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stawka (NDŞ bilen)'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='rate_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stawka (NDŞ-siz)'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='ready_status',
            field=models.CharField(default='ready', max_length=50, verbose_name='Ýüklenmäge taýýarlyk'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='route_info',
            field=models.TextField(blank=True, null=True, verbose_name='Marşrut barada maglumat'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='stealth_mode',
            field=models.BooleanField(default=False, verbose_name='Steýls — belli firmalardan gizle'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='unload_type',
            field=models.CharField(blank=True, choices=[('top', 'Üstden'), ('side', 'Gapdal tarapyndan'), ('rear', 'Yzdan'), ('full_open', 'Doly açylýan tent'), ('crossbar_remove', 'Ştangasy aýrylýan'), ('stand_remove', 'Stoýkasy aýrylýan')], max_length=50, null=True, verbose_name='Düşürme görnüşi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='without_bargain',
            field=models.BooleanField(default=False, verbose_name='Torgsyz'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='delivery_address',
            field=models.CharField(max_length=255, verbose_name='Düşürme ýeri (adres)'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Düşürme senesi'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beýany'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cargos/', verbose_name='Ýük suraty'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='pickup_address',
            field=models.CharField(max_length=255, verbose_name='Ýüklenýän ýer (adres)'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='pickup_date',
            field=models.DateField(verbose_name='Ýüklenme senesi'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('open', 'Açyk'), ('in_progress', 'Ýolda'), ('delivered', 'Gowşuryldy'), ('cancelled', 'Ýatyryldy')], default='open', max_length=30, verbose_name='Ýük ýagdaýy'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ýük ady'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Göwrümi (m³)'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight_kg',
            field=models.PositiveIntegerField(verbose_name='Agramy (kg)'),
        ),
    ]
