# Generated by Django 5.2.7 on 2025-10-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasha', '0010_cargotypedict_readystatusdict_vehicletrucktypedict'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyLoadRequirementDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name_tk', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kuzow we ýükleme talaby',
                'verbose_name_plural': 'Kuzow we ýükleme talaplary',
            },
        ),
    ]
